spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_project
    username: root
    password: root123
  thymeleaf:
    cache: false
    #添加那个目录的文件需要restart
  devtools:
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chen.medicine_mall.pojo
